### ISSUE TITLE
Fix code scanning alert - Clear-text storage of sensitive information

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#214]
Tracking issue for:
- [ ] https://github.com/s-allius/tsun-gen3-proxy/security/code-scanning/3

---
Maybe we can address this by creating the internal configuration directly from the HA configuration instead of storing a temporary config.toml file with the password

**Comment by mime24** [comment]
sounds meaningful. I saw you already startet working on that

**Comment by s-allius** [comment]
fixed with #230
