### ISSUE TITLE
HA AddOn: Dokumentation update

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#220]
For the AddOn, we need a user documentation how to use it.

At least:
- prerequisites for using this AddOn (link to HA description)
- adding our AddOn Repro to the costumer installation
- Update and rollback concept

**Comment by mime24** [comment]
I'll create a short one pager typically implemented in the documentation tab of the add-on. from there I would link to the full documentation.

- describing options and giving examples. 
- describe typical scenario with "Mosquitto" add-on and "AdGuard Home" -add-on

**Comment by s-allius** [comment]
closed with #245
