### ISSUE TITLE
The Compose file './docker-compose.yaml' is invalid

### ISSUE THREAD

**Issue by Lamprecht** [s-allius/tsun-gen3-proxy#84]
I see some errors with the docker-compose.yaml file (checked out from main).
```
docker-compose build
ERROR: The Compose file './docker-compose.yaml' is invalid because:
networks.outside.ipam.config value Additional properties are not allowed ('gateway', 'ip_range' were unexpected)
networks.outside value Additional properties are not allowed ('name' was unexpected)
services.home-assistant.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
```

I think these are incompatibilities with the Version 3 declaration. See this question on [SO](https://stackoverflow.com/questions/69334107/docker-compose-invalid-additional-properties-are-not-allowed)

```
docker -v        
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
docker-compose -v
docker-compose version 1.25.0, build unknown
```

there is also a typo in Line 80 ( '(' should be '{')

**Comment by s-allius** [comment]
Thanks for the hint. I am running my solution on a Synology NAS with a 
Docker version 20.10.23, build 876964a

where I have no problems. My original idea was to not use the default network so that the containers are isolated from others on the machine. I don't have that much experience with Docker, so this approach might be wrong.

I will look for a better solution

**Comment by s-allius** [comment]
Update: On my MAC I only got a warning, that the version will be ignored

```bash
docker -v            
Docker version 26.1.1, build 4cf5afa
docker-compose -v    
Docker Compose version v2.27.0-desktop.2
sallius@stefans-macbook-air tsun % 
```

**Comment by s-allius** [comment]
@Lamprecht 

I fixed the warnings and removed the obsolete version definition. With both of my docker-compose versions, there a no more errors.

Is it possible for you to check the latest version from the dev-0.8.0 branch with your `docker-compose` version?

**Comment by Lamprecht** [comment]
```
Proxy git:(master) > export PROJECT_DIR=/home/chris/devel/TSUN/Proxy
Proxy git:(master) > docker-compose build                           
ERROR: Invalid interpolation format for "home-assistant" option in service "services": "${PROJECT_DIR:-./}homeassistant/config:/config"
```

**Comment by Lamprecht** [comment]
Trying with docker-compose-v2:
```
> /usr/libexec/docker/cli-plugins/docker-compose -v
Docker Compose version 2.20.2+ds1-0ubuntu1~20.04.1
> /usr/libexec/docker/cli-plugins/docker-compose up
... lots of pull messages snipped
network home-assistant declared as external, but could not be found
```

**Comment by s-allius** [comment]
You probably want to add a slash after:
`export PROJECT_DIR=/home/chris/devel/TSUN/Proxy`

so your path results to:
`/home/chris/devel/TSUN/Proxy/homeassistant/config`

But that is certainly not the problem. I'll have another look tomorrow

**Comment by s-allius** [comment]
Now I removed the network definition completely. 

Can you give the latest version of the dev-0.8.0 branch another try?

**Comment by Lamprecht** [comment]
Yes, works now!
Thank you very much!

**Comment by s-allius** [comment]
Cool. Thank you very much for your support.
I had never seen the problem before. For the future I now have a check in the build script, so that errors should be noticed directly
